# Generated by Django 3.2.8 on 2021-10-18 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ledgerAccount',
            fields=[
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_description', models.CharField(max_length=100)),
                ('normal_side', models.FloatField()),
                ('account_category', models.CharField(max_length=100)),
                ('account_subcategory', models.CharField(max_length=100)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('balance', models.FloatField()),
                ('date_account_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.FloatField()),
                ('statement', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
