# Generated by Django 3.2.8 on 2021-12-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0002_auto_20211207_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_number',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
