# Generated by Django 3.2.8 on 2021-12-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0003_alter_ledgeraccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_subcategory',
            field=models.CharField(blank=True, choices=[('CURRRENT ASSETS', 'CURRRENT ASSETS'), ('FIXED ASSETS', 'FIXED ASSETS'), ('LONG TERM ASSETS', 'LONG TERM ASSETS'), ('ACCOUNTS RECIEVABLE', 'ACCOUNTS RECIEVABLE'), ('CURRENT LIABILITIES', 'CURRENT LIABILITIES'), ('PAYROLL LIABILITIES', 'PAYROLL LIABILITIES'), ('LONG TERM LIABILITIES', 'LONG TERM LIABILITIES'), ('NOTES PAYABLE', 'NOTES PAYABLE'), ('ACCRUED EXPENSES', 'ACCRUED EXPENSES'), ('DEFFERED REVENUE', 'DEFFERED REVENUE'), ('COMMON STOCK', 'COMMON STOCK'), ('PREFERRED STOCK', 'PREFERRED STOCK'), ('RETAINED EARNINGS', 'RETAINED EARNINGS'), ('DIVIDENDS', 'DIVIDENDS'), ('TREASURY STOCK', 'TREASURY STOCK')], max_length=100),
        ),
    ]
