# Generated by Django 3.2.8 on 2021-12-10 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0007_journal_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
