# Generated by Django 4.0 on 2021-12-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0008_journal_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='date_added',
        ),
    ]
