# Generated by Django 4.0 on 2021-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0010_rename_balance_journal_journal_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_name',
            field=models.CharField(max_length=50),
        ),
    ]
