# Generated by Django 4.0 on 2021-12-11 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0012_alter_journalentry_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='date_account_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
