# Generated by Django 4.0 on 2021-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0013_alter_ledgeraccount_date_account_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
