# Generated by Django 4.0 on 2021-12-12 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0014_journalentry_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgeraccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_number',
            field=models.IntegerField(default=0, max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='date_account_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='normal_side',
            field=models.CharField(blank=True, choices=[('RIGHT', 'RIGHT'), ('LEFT', 'LEFT')], max_length=5),
        ),
    ]
