# Generated by Django 4.0 on 2021-12-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerAccount', '0016_alter_journalentry_normal_side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='journal',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
