# Generated by Django 3.2.8 on 2021-10-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
