# Generated by Django 3.2.8 on 2021-11-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211017_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_date',
            field=models.DateField(default=None),
        ),
    ]
