# Generated by Django 3.2.8 on 2021-11-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_password_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password_date',
        ),
    ]
